name: Update Instagram Posts
on:
  schedule:
    - cron: '0 0 * * *' # 毎日24時（日本時間だと朝9時）に更新
  workflow_dispatch: # 手動で即座に更新したい時用

jobs:
  update-readme:
    name: Update README with Instagram Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Instagram Posts
        uses: snehanshu/instagram-readme-action@v1.4.0
        with:
          # カッコを外して、クォーテーションで囲むのが一番安全です
          username: 'utakik'
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update Instagram posts" || exit 0
          git push
